### ISSUE TITLE
DPUB-ARIA support

### ISSUE THREAD

**Issue by Seirdy** [opena11y/evaluation-library#3]
I'd love to see DPUB-ARIA support in OpenA11y Evaluation Library and AInspector. Currently, it flags all DPUB-ARIA roles as invalid.

I noticed the issue on my own website, where I make heavy use of DPUB-ARIA. Here's a sample page: https://seirdy.one/posts/2022/06/10/cli-best-practices/

Roles like `doc-noteref`, `doc-endnotes`, and `doc-backlink` are very common in various SSG and CMS implementations.

**Comment by jongund** [comment]
Thank you for your feature request.
I will look into this for the next version of the library.

**Comment by jongund** [comment]
There are no resources to do this at this time.
